### DISCUSSION TITLE
Having trouble with signals using xdg portals.

### DISCUSSION THREAD

**Discussion by MineBill** [dbus-cxx/dbus-cxx#156] [Q&A]
Hi, i wanted to use your library to utilize cross-desktop operations(file picking, notification etc) through xdg portals. I created a small example to test [org.freedesktop.portal.FileChooser.OpenFile](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html#org-freedesktop-portal-filechooser-openfile). This method returns an object path to a [Request](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Request.html#org-freedesktop-portal-request) interface, which can be used to get the actual results. Here is the code i tried, on my KDE system:
```cpp
#include <condition_variable>
#include <cstdint>
#include <mutex>
#include <print>
#include <random>

#include "dbus-cxx/standalonedispatcher.h"
#include "dbus-cxx/variant.h"
#include <dbus-cxx.h>
#include <sys/types.h>

using OpenFileFn = DBus::Path(std::string, std::string, std::map<std::string, DBus::Variant>);
using OpenFileResponse = void(uint32_t response, std::map<std::string, DBus::Variant>);

namespace {
    std::random_device g_RandomDevice;
    std::mt19937 g_Engine(g_RandomDevice());
}

std::condition_variable g_Completed;
std::mutex g_Mutex;

int main()
{
    std::shared_ptr<DBus::Dispatcher> dispatcher = DBus::StandaloneDispatcher::create();
    std::shared_ptr<DBus::Connection> conn = dispatcher->create_connection(DBus::BusType::SESSION);

    auto object = conn->create_object_proxy("org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop");

    DBus::MethodProxy<OpenFileFn>& OpenFile = *(object->create_method<OpenFileFn>("org.freedesktop.portal.FileChooser", "OpenFile"));

    std::map<std::string, DBus::Variant> options {};
    // options["handle_token"] = token;

    auto path = OpenFile("/", "Select a file", options);
    std::println("Path is {}", path.c_str());

    auto requestProxy = conn->create_object_proxy("org.freedesktop.portal.Desktop", path);
    auto requestSignal = requestProxy->create_signal<OpenFileResponse>("org.freedesktop.portal.Request", "Response");
    // std::println("{}", signal2->connection()->unique_name());
    requestSignal->connect([](uint32_t response, std::map<std::string, DBus::Variant> data) {
        std::println("Callback called: {} {}", response, data.size());
        g_Completed.notify_all();
    });
    conn->flush();

    std::println("Waiting for callback");
    std::unique_lock lock(g_Mutex);
    g_Completed.wait(lock);

    std::println("Finished");
}
```

However, the problem i am encountering is that successful operation do not trigger the signal but when the user cancels the file dialog, the signal is correctly triggered with the response code set to 1.

I initially thought this was some kind of KDE bug, but i tried another example using libdbus, which produces the expected results: the signal always gets triggered:
```cpp
#include <cstdlib>
#include <dbus/dbus.h>
#include <iostream>
#include <string>
#include <vector>

#define MARKER printf("marker %d\n", __LINE__)

class DbusHelper {
public:
    DbusHelper()
    {
        dbus_error_init(&dbus_error_);
        connection_ = dbus_bus_get(DBUS_BUS_SESSION, &dbus_error_);
        if (dbus_error_is_set(&dbus_error_)) {
            std::cerr << "Connection Error (" << dbus_error_.message << ")"
                      << std::endl;
            dbus_error_free(&dbus_error_);
            exit(1);
        }
        if (!connection_) {
            std::cerr << "Failed to open connection to session bus." << std::endl;
            exit(1);
        }
    }

    ~DbusHelper()
    {
        if (connection_) {
            dbus_connection_unref(connection_);
        }
    }

    void OpenFilePicker()
    {
        DBusMessage* message;
        DBusMessageIter args;
        message = dbus_message_new_method_call(
            "org.freedesktop.portal.Desktop",     // destination
            "/org/freedesktop/portal/desktop",    // path
            "org.freedesktop.portal.FileChooser", // interface
            "OpenFile"                            // method
        );

        if (!message) {
            std::cerr << "Message Null Error" << std::endl;
            return;
        }

        // Appending the required arguments: app_id, parent window, and options
        dbus_message_iter_init_append(message, &args);
        char const* windowTitle = "com.example.FilePicker";
        char const* parent_window = "/";
        dbus_message_iter_append_basic(&args, DBUS_TYPE_STRING,
            &parent_window);
        dbus_message_iter_append_basic(&args, DBUS_TYPE_STRING, &windowTitle);

        // Append options (empty dictionary)
        DBusMessageIter dict;
        dbus_message_iter_open_container(&args, DBUS_TYPE_ARRAY, "{sv}", &dict);
        dbus_message_iter_close_container(&args, &dict);

        // Send the method call
        DBusPendingCall* pending;
        if (!dbus_connection_send_with_reply(connection_, message, &pending, -1)) {
            std::cerr << "Failed to send message" << std::endl;
            dbus_message_unref(message);
            return;
        }

        if (pending == nullptr) {
            std::cerr << "Pending call null." << std::endl;
            dbus_message_unref(message);
            return;
        }

        dbus_connection_flush(connection_);
        dbus_message_unref(message);

        // Wait for the pending call
        dbus_pending_call_block(pending);

        // Get the reply message
        DBusMessage* reply = dbus_pending_call_steal_reply(pending);
        if (!reply) {
            std::cerr << "Reply Null Error" << std::endl;
            dbus_pending_call_unref(pending);
            return;
        }

        // Extract the path to the Request object
        char const* request_path;
        if (!dbus_message_get_args(reply, &dbus_error_, DBUS_TYPE_OBJECT_PATH,
                &request_path, DBUS_TYPE_INVALID)) {
            std::cerr << "Failed to get Request Path" << std::endl;
            dbus_error_free(&dbus_error_);
        }

        // Add match to receive the response signal
        AddMatchForRequest(request_path);

        dbus_pending_call_unref(pending);
        dbus_message_unref(reply);
    }

    void AddMatchForRequest(std::string const& request_path)
    {
        std::string match = "type='signal',interface='org.freedesktop.portal.Request',path='" + request_path + "'";
        dbus_bus_add_match(connection_, match.c_str(), &dbus_error_);
        if (dbus_error_is_set(&dbus_error_)) {
            std::cerr << "Match Error: " << dbus_error_.message << std::endl;
            dbus_error_free(&dbus_error_);
        }
    }

    void ProcessEvents()
    {
        while (true) {
            dbus_connection_read_write(connection_, 1000);
            DBusMessage* message = dbus_connection_pop_message(connection_);
            if (message == nullptr) {
                continue;
            }

            // Handle the "Response" signal
            if (dbus_message_is_signal(message, "org.freedesktop.portal.Request",
                    "Response")) {
                HandleResponse(message);
                break;
            }

            dbus_message_unref(message);
        }
    }

    void HandleResponse(DBusMessage* message)
    {
        DBusMessageIter args;
        if (!dbus_message_iter_init(message, &args)) {
            std::cerr << "Message has no arguments!" << std::endl;
            return;
        }

        int response_code;
        dbus_message_iter_get_basic(&args, &response_code);
        printf("response code: %d\n", response_code);
    }

private:
    DBusConnection* connection_;
    DBusError dbus_error_;
};

int main()
{
    DbusHelper dbus_helper;

    // Open the file picker dialog
    dbus_helper.OpenFilePicker();

    // Process events until we receive the response
    dbus_helper.ProcessEvents();

    return 0;
}
```

Please note this example was generated through ChatGPT because i didn't want to spend time learning the libdbus API.

Even weirder, trying the original example on Gnome, also produced the correct results.

I used `dbus-monitor` to inspect what was happening and as far as i can tell, there were no differences between dbus-cxx and libdbus, so i can only assume i am misusing your library.

Maybe this is a bit too much, so please let me know of any additional information i can provide.

**Comment by rm5248** [comment]
Could you add a capture from `dbus-monitor` when you do the action with libdbus and when you do it with dbus-cxx?  (e.g. use `dbus-monitor --pcap`).  It's probably something to do with the signal handling, but I don't see what it could be at the moment.

**Reply by MineBill** [reply]
[dbus_cxx.txt](https://github.com/user-attachments/files/17360906/dbus_cxx.txt)
[libdbus.txt](https://github.com/user-attachments/files/17360907/libdbus.txt)
I attached the captures, which i changed the extension to `txt` since Github didn't like `pcap`. In both of them, i start the capture, run the app, select a file named `Fedora-Workstation-Live-x86_64-41_Beta-1.2.iso`, run the app again but this time close the picker without selecting a file and then stop the capture.

**Comment by rm5248** [comment]
It looks like you're trying to be a bit too specific with the dbus match that is being made.

This seems to be the relevant call to listen for the signal - notice how it has an extra member(`Request`) in dbus-cxx:

![image](https://github.com/user-attachments/assets/740f0505-a1d8-4ddf-b416-30692948d3e2)

Without looking too much more into the dbus specification for this service, I bet you could change the following line and have it work:
```
auto requestSignal = requestProxy->create_signal<OpenFileResponse>("org.freedesktop.portal.Request", "Response");
```
```
auto requestSignal = requestProxy->create_signal<OpenFileResponse>("org.freedesktop.portal.Request", "");
```

**Reply by MineBill** [reply]
Unfortunately that didn't help. Even changing the libdbus example and adding the Response member didn't stop it from working, so i assume it doesn't matter how specific the match is.

**Comment by MineBill** [comment]
Progress! I had an idea that maybe the signal wasn't getting called because it somehow failed to match the parameters. So i removed the `std::map<std::string, DBus::Variant>` from the `OpenFileResponse` type, leaving only the `uint32_t response` and it works! I immediately get a response `0` when i select a files and `1` when i don't. So parsing the dictionary must be failing in some way. I also run the same program on Gnome, which run perfectly fine with the map, so i got another pcap capture: [dbus_cxx_gnome.txt](https://github.com/user-attachments/files/17373917/dbus_cxx_gnome.txt). Non-empty response with picked files are `No. 375`  in `dbus_cxx.pcap` file i provided earlier and `No. 587` in the Gnome capture i attached.

**Reply by rm5248** [reply]
It looks like the parsing is failing.  It's probably throwing an exception and swallowing it someplace.  Can you turn on the logging and see? https://dbus-cxx.github.io/runtime-configuration.html#autotoc_md53

**Reply by MineBill** [reply]
Here is what is logged after the Response signal is triggered:
```
DBus.StandaloneDispatcher: Dispatching connections
DBus.Connection: Try to read a message
DBus.priv.SendmsgTransport: Have 32 bytes of control after real reading
DBus.Signature: Signature 'o' is valid
DBus.Signature: Signature 'o' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 'g' is valid
DBus.Signature: Signature 'ua{sv}' is valid
DBus.Signature: Signature 'g' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Signature: Signature 's' is valid
DBus.Message: Creating SignalMessage from data
DBus.Message: Message has 0 fds
DBus.Signature: Signature 'ua{sv}' is valid
DBus.Message: Following message created from the data: DBus::Message = [SignalMessage
  Message length: 153
  Endianess: Little
  Serial: 11014
  Headers:
    Path: /org/freedesktop/portal/desktop/request/1_1219/t
    Interface: org.freedesktop.portal.Request
    Member: Response
    Destination: :1.1219
    Sender: :1.26
    Signature: DBus::Signature[ua{sv}]
]
DBus.signal_proxy: DBus::signal_proxy<void (unsigned int,std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, DBus::Variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, DBus::Variant> > >)>::on_dbus_incoming method=Response
DBus.Signature: Signature 'ua{sv}' is valid
DBus.MessageIterator: Extracting array.  new position: 8 array len: 145 array end pos: 153
DBus.MessageIterator: Current offset: 8 last array pos: 153
DBus.MessageIterator: Extracting DICT or STRUCT: aligning to 8 byte boundary.  Location: 8
DBus.MessageIterator: Current offset: 8 last array pos: 153
DBus.Signature: Either stack not empty or signature not used up completely
DBus.Signature: Signature '(sa(us))' is invalid
DBus.Variant: Creating Variant from signature DBus::Signature[(sa(us))].  Current offset after alignment: 37
DBus.signal_proxy: Unknown exception
DBus.StandaloneDispatcher: done dispatching
```
